document.write('<section>');
document.write('<h3>'); 
document.write('Mas información sobre el navegador');
document.write('</h3>');
document.write('<p>'); 
document.write('Versión: ' + info_nav.version);
document.write('</p>');
document.write('<p>'); 
document.write('Plataforma: ' + info_nav.plataforma);
document.write('</p>');
document.write('<p>'); 
document.write('Vendedor: ' + info_nav.vendedor);
document.write('</p>');
document.write('<p>'); 
document.write('Agente: ' + info_nav.agente);
document.write('</p>');
document.write('<p>'); 
document.write('¿Javascript activo?: ' + info_nav.jsActivo);
document.write('</p>');
document.write('</section>');
